export const ACHIEVEMENTS = [
  {
    id: 'first_survivor',
    title: '¡Primer Superviviente!',
    description: 'Trata a tu primer paciente correctamente',
    icon: '🏥',
    secret: false,
  },
  {
    id: 'carbapenem_master',
    title: 'Maestro del Carbapenémico',
    description: 'Trata correctamente 10 pacientes KPC',
    icon: '💊',
    trackKey: 'kpc_treated',
    threshold: 10,
  },
  {
    id: 'mbl_fighter',
    title: 'Luchador MBL',
    description: 'Sobrevive tu primer encuentro con MBL',
    icon: '🧬',
  },
  {
    id: 'panresistant_slayer',
    title: 'Asesino Panresistente',
    description: 'Trata correctamente un paciente con todos los mecanismos',
    icon: '💀',
  },
  {
    id: 'marathon_runner',
    title: 'Maratonista Hospitalario',
    description: 'Corre 2000m en una sola partida',
    icon: '🏃',
    trackKey: 'distance',
    threshold: 2000,
  },
  {
    id: 'perfect_prescription',
    title: 'Receta Perfecta',
    description: 'Completa una fase antibiótica sin atrapar ningún antibiótico incorrecto',
    icon: '✅',
  },
  {
    id: 'combo_doctor',
    title: 'Doctor Combo x5',
    description: 'Atrapa 5 antibióticos correctos consecutivos',
    icon: '🔥',
    trackKey: 'streak',
    threshold: 5,
  },
  {
    id: 'speed_demon',
    title: 'Demonio de Velocidad',
    description: 'Alcanza el nivel 6 de mecanismos en una partida',
    icon: '⚡',
  },
  {
    id: 'gold_hunter',
    title: 'Cazador de Oro',
    description: 'Atrapa ATM-AVI o CAZ+ATM 5 veces',
    icon: '⭐',
    trackKey: 'gold_caught',
    threshold: 5,
  },
  {
    id: 'rich_doctor',
    title: 'Doctor Adinerado',
    description: 'Acumula 500 Coreimcitos en total',
    icon: '💰',
    trackKey: 'total_coins',
    threshold: 500,
  },
];

export const DAILY_CHALLENGES = [
  { id: 'treat_3_mbl',    text: 'Trata 3 pacientes MBL hoy',               type: 'patients_mech',  mechanism: 'MBL',  target: 3,  reward: 30  },
  { id: 'run_2000m',      text: 'Corre 2000m en una partida',              type: 'distance',                           target: 2000, reward: 25 },
  { id: 'catch_10_green', text: 'Atrapa 10 antibióticos activos',          type: 'green_abs',                          target: 10, reward: 20  },
  { id: 'reach_level5',   text: 'Alcanza el nivel MBL en una partida',     type: 'reach_level',                        target: 5,  reward: 20  },
  { id: 'clean_phase',    text: 'Completa una fase sin rojos',             type: 'clean_phase',                        target: 1,  reward: 25  },
  { id: 'collect_50',     text: 'Recoge 50 Coreimcitos en una partida',    type: 'coins_run',                          target: 50, reward: 15  },
  { id: 'treat_kpc',      text: 'Trata 2 pacientes KPC',                   type: 'patients_mech',  mechanism: 'KPC',  target: 2,  reward: 20  },
  { id: 'gold_combo',     text: 'Usa CAZ+ATM o ATM-AVI 2 veces',          type: 'gold_abs',                           target: 2,  reward: 30  },
];

export const EDUCATIONAL_FACTS = [
  'Las MBL (NDM, VIM, IMP) hidrolizan TODOS los betalactámicos excepto aztreonam.',
  'CAZ-AVI+ATM y ATM-AVI son las únicas opciones activas frente a los 5 mecanismos.',
  'Las carbapenemasas KPC (clase A) se inhiben por avibactam, vaborbactam y relebactam.',
  'OXA-48 pertenece a las oxacilinasas (clase D) y se inhibe por avibactam.',
  'Las BLEE hidrolizan penicilinas y cefalosporinas de 3ª/4ª gen. pero NO carbapenémicos.',
  'Sulbactam-durlobactam es activo frente a A. baumannii, pero no frente a Enterobacterales.',
  'Cefiderocol utiliza receptores de hierro bacterianos para penetrar la membrana externa.',
  'Las MBL son zinc-dependientes y NO se inhiben por avibactam, vaborbactam ni relebactam.',
  'La combinación CAZ-AVI+ATM: el aztreonam no es hidrolizado por MBL, y CAZ-AVI lo protege de BLEE/KPC/OXA.',
  'K. pneumoniae es el principal productor mundial de KPC (Klebsiella pneumoniae Carbapenemase).',
  'La transmisión de resistencias entre bacterias ocurre principalmente por plásmidos conjugativos.',
  'El fenotipo BLEE se detecta en laboratorio por sinergia con ácido clavulánico (test de disco combinado).',
  'NDM = New Delhi Metallo-β-lactamase; fue descrita por primera vez en 2009 en Nueva Delhi.',
  'Las carbapenemasas de clase B (MBL) requieren iones Zn²⁺ como cofactor catalítico.',
  'El término XDR (extremadamente resistente) implica resistencia a ≥1 agente en ≥3 clases antibióticas.',
];
